[package]
name = "http-api-bindings"
version = "0.8.2"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tabby-inference = { version = "0.8.0-rc.0", path = "../tabby-inference" }
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
